import { spawn } from "node:child_process";
import { createReadStream, createWriteStream } from "node:fs";
import {
  mkdir,
  readFile,
  writeFile,
  open,
  rm,
  mkdtemp,
  copyFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { randomUUID, createHash } from "node:crypto";
import { isDeepStrictEqual } from "node:util";
import { parse } from "pgsql-parser";
import {
  PROFILE,
  validateAtomic,
  validateChecks,
  fingerprint,
  assertExecutionEnvironment,
} from "./target-policy.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const artifacts = join(root, "artifacts", "rehearsals");
const lockPath = join(artifacts, "active.lock");
const sourceContainer = "migration-flight-recorder-postgres";
const sourceDatabase = "migration_flight_recorder";
const labelKey = "mfr.rehearsal.run";
const maxBytes = 1024 ** 3;
const quote = (value) => '"' + value.replaceAll('"', '""') + '"';
const hash = (value) => createHash("sha256").update(value).digest("hex");

// No shell interpolation. Docker command arguments are generated by this module.
function command(
  args,
  { input, inputFile, outputFile, env, timeout = 60_000, signal } = {},
) {
  return new Promise((resolvePromise, reject) => {
    const child = spawn("docker", args, {
      env: { ...process.env, ...env },
      stdio: ["pipe", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    let failure;
    const stop = () => {
      failure = new Error("Rehearsal interrupted");
      child.kill("SIGKILL");
    };
    const timer = setTimeout(
      () => {
        failure = new Error("Command deadline exceeded");
        child.kill("SIGKILL");
      },
      Math.max(1, timeout),
    );
    signal?.addEventListener("abort", stop, { once: true });
    if (signal?.aborted) stop();
    const output = outputFile
      ? createWriteStream(outputFile, { mode: 0o600 })
      : null;
    if (output) {
      child.stdout.pipe(output);
      output.on("error", (error) => {
        failure = error;
        child.kill("SIGKILL");
      });
    } else
      child.stdout.on("data", (chunk) => {
        stdout += chunk;
        if (Buffer.byteLength(stdout) > 16 * 1024 ** 2) {
          failure = new Error("Evidence output limit exceeded");
          child.kill("SIGKILL");
        }
      });
    child.stderr.on("data", (chunk) => {
      stderr = (stderr + chunk).slice(-65536);
    });
    child.stdin.on("error", () => {});
    let stream;
    if (inputFile) {
      stream = createReadStream(inputFile);
      stream.on("error", (error) => {
        failure = error;
        child.kill("SIGKILL");
      });
      stream.pipe(child.stdin);
    } else child.stdin.end(input);
    child.on("error", (error) => {
      failure = error;
    });
    child.on("close", async (code) => {
      clearTimeout(timer);
      signal?.removeEventListener("abort", stop);
      stream?.destroy();
      if (output && !output.closed)
        await new Promise((done) => {
          output.once("close", done);
        });
      if (failure || code !== 0) {
        const error =
          failure ??
          new Error(stderr.trim() || `Docker command failed (${code})`);
        Object.assign(error, { stdout, stderr, exitCode: code });
        reject(error);
      } else resolvePromise({ stdout, stderr, exitCode: code });
    });
  });
}

async function sourceEnvironment() {
  let uri = process.env.REHEARSAL_SOURCE_URL;
  if (!uri) {
    const file = await readFile(join(root, "sandbox", ".env"), "utf8").catch(
      () => "",
    );
    uri = file
      .split("\n")
      .find((line) => line.startsWith("REHEARSAL_SOURCE_URL="))
      ?.slice("REHEARSAL_SOURCE_URL=".length)
      .trim();
  }
  if (!uri)
    throw new Error(
      "Set REHEARSAL_SOURCE_URL or configure sandbox/.env; no credentials are inferred.",
    );
  const url = new URL(uri);
  if (
    !["postgres:", "postgresql:"].includes(url.protocol) ||
    !["localhost", "127.0.0.1"].includes(url.hostname) ||
    url.port !== "54329" ||
    url.pathname !== "/" + sourceDatabase ||
    url.search
  ) {
    throw new Error(
      "Source must be the allowlisted local demo database on port 54329, without URI options.",
    );
  }
  return {
    PGUSER: decodeURIComponent(url.username),
    PGPASSWORD: decodeURIComponent(url.password),
    PGOPTIONS: "-c default_transaction_read_only=on -c statement_timeout=60000",
  };
}

const sourceArgs = [
  "exec",
  "-i",
  "-e",
  "PGUSER",
  "-e",
  "PGPASSWORD",
  "-e",
  "PGOPTIONS",
  sourceContainer,
];
export async function sourceQuery(sql) {
  // Internal diagnostics/tests only; source sessions force read-only transactions.
  const env = await sourceEnvironment();
  return (
    await command(
      [
        ...sourceArgs,
        "psql",
        "-X",
        "-h",
        "127.0.0.1",
        "-d",
        sourceDatabase,
        "-At",
        "-v",
        "ON_ERROR_STOP=1",
      ],
      { input: sql, env },
    )
  ).stdout.trim();
}

export function assertSourceSize(bytes) {
  if (!Number.isFinite(bytes) || bytes < 0 || bytes > maxBytes)
    throw new Error(
      "Source exceeds the 1 GiB limit or size is unknown; an alternative clone strategy is required. No sampling performed.",
    );
}

// Shared restore boundary; exported for a failure-propagation unit test.
export async function restoreArchive(exec, archive) {
  return exec(
    [
      "pg_restore",
      "-U",
      "rehearsal_owner",
      "-d",
      "rehearsal",
      "--no-owner",
      "--no-acl",
      "--exit-on-error",
    ],
    { inputFile: archive },
  );
}

const permitted = new Set([
  "AlterTableStmt",
  "CreateStmt",
  "IndexStmt",
  "InsertStmt",
  "UpdateStmt",
  "DeleteStmt",
  "TruncateStmt",
  "CommentStmt",
  "RenameStmt",
  "CreateSchemaStmt",
  "CreateSeqStmt",
  "AlterSeqStmt",
  "ViewStmt",
  "CreateFunctionStmt",
  "DoStmt",
  "SelectStmt",
  "DropStmt",
  "TransactionStmt",
]);
export async function parseMigration(sql) {
  if (
    typeof sql !== "string" ||
    !sql.trim() ||
    Buffer.byteLength(sql) > 1024 * 1024
  )
    throw new Error("Migration must contain 1 byte to 1 MiB of SQL.");
  const tree = await parse(sql); // PostgreSQL grammar, never a semicolon splitter.
  const bytes = Buffer.from(sql);
  const statements = (tree.stmts ?? []).map((raw) => {
    const kind = Object.keys(raw.stmt)[0];
    if (!permitted.has(kind))
      throw new Error(`Unsupported/admin statement: ${kind}`);
    if (
      kind === "DropStmt" &&
      ![
        "OBJECT_TABLE",
        "OBJECT_INDEX",
        "OBJECT_VIEW",
        "OBJECT_SEQUENCE",
        "OBJECT_SCHEMA",
        "OBJECT_FUNCTION",
        "OBJECT_TYPE",
      ].includes(raw.stmt.DropStmt.removeType)
    )
      throw new Error("Administrative DROP is unavailable.");
    const transaction = raw.stmt.TransactionStmt?.kind;
    if (
      transaction &&
      ![
        "TRANS_STMT_BEGIN",
        "TRANS_STMT_START",
        "TRANS_STMT_COMMIT",
        "TRANS_STMT_ROLLBACK",
        "TRANS_STMT_SAVEPOINT",
        "TRANS_STMT_RELEASE",
        "TRANS_STMT_ROLLBACK_TO",
      ].includes(transaction)
    )
      throw new Error("Prepared transactions are unavailable.");
    const start = raw.stmt_location ?? 0;
    return {
      kind,
      transaction,
      sql: bytes
        .subarray(start, raw.stmt_len ? start + raw.stmt_len : bytes.length)
        .toString("utf8")
        .trim(),
    };
  });
  if (!statements.length) throw new Error("No SQL statements found.");
  return statements;
}

function markdown(report) {
  const statements = report.execution.statements
    .map((s) => `| ${s.index} | ${s.kind} | ${s.status} | ${s.milliseconds} |`)
    .join("\n");
  const changedRows =
    report.diff?.tables.filter((t) => t.beforeRows !== t.afterRows) ?? [];
  const checks = report.verification.checks
    .map(
      (c) =>
        `### ${c.name ?? "Postcondition"} — ${c.passed ? "PASS" : "FAIL"}\n\n\`\`\`sql\n${c.sql}\n\`\`\`\n\nExpected: \`${JSON.stringify(c.expectedRows)}\`\n\nActual: \`${JSON.stringify(c.actualRows ?? { error: c.error })}\`\n`,
    )
    .join("\n");
  return `# Sandbox rehearsal ${report.runId}\n\nStatus: ${report.status}\n\nMigration execution: ${report.execution.status} · Verification: ${report.verification.status}\n\nTarget execution: **NOT_AVAILABLE**\n\nThis is a full-copy local demo rehearsal, not production safety certification.\n\n## Clone\n\n- Source: ${report.source.database}\n- PostgreSQL: ${report.source.version ?? "not established"}\n- Coverage: ${report.clone.coverage}; source size: ${report.source.bytes ?? "unknown"} bytes\n- Snapshot interval: ${report.clone.snapshotStartedAt ?? "not started"} — ${report.clone.snapshotFinishedAt ?? "not finished"}\n- Restore: ${report.clone.restore ?? "not completed"}\n- Network: none; maximum 2 CPUs / 2 GiB memory\n- Cleanup: ${report.cleanup}\n\n## Migration evidence\n\nSQL SHA-256: \`${report.sqlSha256}\`\n\nExact input: [migration.sql](migration.sql). Full structured evidence, before/after schema, command results, and errors: [report.json](report.json).\n\n| Statement | Kind | Outcome | Time (ms) |\n| --- | --- | --- | --- |\n${statements}\n\nTransaction at disconnect: ${report.execution.transactionAtDisconnect ?? "not started"}. Completed statements are not necessarily committed: consult the transaction outcome and recorded after-state.\n\nSchema changed: ${report.diff?.schemaChanged ?? "not verified"}. Invalid indexes after rehearsal: ${JSON.stringify(report.diff?.invalidIndexes ?? "not verified")}.\n\nRow-count changes: \`${JSON.stringify(changedRows)}\`\n\n${report.error || report.execution.error ? "Error: " + (report.error ?? report.execution.error.message) + "\n\n" : ""}## Explicit postconditions\n\n${checks || "No postconditions supplied; business semantics remain unverified.\n"}\n## Limitations\n\n${report.limitations.map((item) => "- " + item).join("\n")}\n`;
}

async function removeSandbox(name, id) {
  let info;
  try {
    info = JSON.parse((await command(["inspect", name])).stdout)[0];
  } catch (error) {
    if (/No such (object|container)/i.test(error.stderr ?? "")) return;
    throw error;
  }
  if (info.Config.Labels?.[labelKey] !== id || name !== `mfr-rehearsal-${id}`)
    throw new Error("Cleanup ownership check failed.");
  await command(["rm", "-f", "-v", name]);
}

export async function cleanupInterrupted() {
  await mkdir(artifacts, { recursive: true, mode: 0o700 });
  const lock = JSON.parse(await readFile(lockPath, "utf8").catch(() => "null"));
  if (lock) {
    try {
      process.kill(lock.pid, 0);
      throw new Error("A rehearsal process is still active; cleanup refused.");
    } catch (error) {
      if (error.code !== "ESRCH") throw error;
    }
  }
  const names = (
    await command([
      "ps",
      "-a",
      "--filter",
      `label=${labelKey}`,
      "--format",
      "{{.Names}}",
    ])
  ).stdout
    .trim()
    .split("\n")
    .filter(Boolean);
  for (const name of names) {
    const id = name.slice("mfr-rehearsal-".length);
    if (!/^[a-f0-9-]{36}$/.test(id))
      throw new Error("Unexpected labeled resource; manual review required.");
    await removeSandbox(name, id);
  }
  if (lock) {
    if (
      lock.temp &&
      dirname(lock.temp) === tmpdir() &&
      lock.temp.startsWith(join(tmpdir(), "mfr-rehearsal-"))
    )
      await rm(lock.temp, { recursive: true, force: true });
    await rm(lockPath);
  }
  return { removedContainers: names, reportsRetained: true };
}

export async function runRehearsal({
  proposedSql,
  checks = [],
  executionProfile = "submitted-transactions",
  backupOnly = false,
}) {
  if (typeof proposedSql !== "string")
    throw new Error("proposedSql must be a string.");
  const runId = randomUUID();
  const name = `mfr-rehearsal-${runId}`;
  await mkdir(artifacts, { recursive: true, mode: 0o700 });
  const lock = await open(lockPath, "wx", 0o600).catch((error) => {
    throw new Error(
      error.code === "EEXIST"
        ? "Another rehearsal or interrupted-run lock exists. Use rehearsal:cleanup after checking the previous run."
        : error.message,
    );
  });
  const directory = join(artifacts, runId);
  let temp;
  let cleanupOK = true;
  const controller = new AbortController();
  const onSignal = () => controller.abort();
  process.once("SIGINT", onSignal);
  process.once("SIGTERM", onSignal);
  const started = Date.now();
  const deadline = started + 600_000;
  const timer = setTimeout(onSignal, 600_000);
  const report = {
    runId,
    startedAt: new Date(started).toISOString(),
    sqlSha256: hash(proposedSql),
    status: "PREPARING",
    source: { container: sourceContainer, database: sourceDatabase },
    clone: {
      container: name,
      database: "rehearsal",
      coverage: "FULL_DATABASE",
      network: "none",
      cpus: 2,
      memoryBytes: 2 * 1024 ** 3,
    },
    execution: { status: "NOT_RUN", statements: [] },
    verification: { status: "NOT_RUN", checks: [] },
    targetExecution: "NOT_AVAILABLE",
    limitations: [
      "No production load or timing equivalence.",
      "Only explicit postconditions validate business semantics.",
      "Concurrent source writes can make later observations differ from the clone snapshot.",
      "SQL parser version 18; the matching source server remains the authority for PostgreSQL 16 compatibility.",
    ],
  };
  report.executionProfile = executionProfile;
  const run = (args, options = {}) =>
    command(args, {
      ...options,
      timeout: Math.min(
        options.timeout ?? 120_000,
        Math.max(1, deadline - Date.now()),
      ),
      signal: controller.signal,
    });
  const exec = (program, options) =>
    run(["exec", "-i", "--user", "postgres", name, ...program], options);
  const psql = (sql, user = "rehearsal_owner") =>
    exec(
      [
        "psql",
        "-X",
        "-q",
        "-U",
        user,
        "-d",
        "rehearsal",
        "-At",
        "-v",
        "ON_ERROR_STOP=1",
      ],
      { input: sql },
    );
  const jsonQuery = async (sql) => JSON.parse((await psql(sql)).stdout.trim());
  async function snapshot() {
    const schema = (
      await exec([
        "pg_dump",
        "-U",
        "rehearsal_owner",
        "-d",
        "rehearsal",
        "--schema-only",
        "--no-owner",
        "--no-acl",
      ])
    ).stdout.replace(/^\\(?:un)?restrict .*$/gm, "");
    const tables = await jsonQuery(
      "SELECT coalesce(json_agg(x ORDER BY schema, name),'[]') FROM (SELECT n.nspname AS schema,c.relname AS name FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.relkind IN ('r','p') AND n.nspname NOT LIKE 'pg_%' AND n.nspname <> 'information_schema') x;",
    );
    const counts = [];
    for (const table of tables)
      counts.push({
        ...table,
        rows: Number(
          (
            await psql(
              `SELECT count(*) FROM ${quote(table.schema)}.${quote(table.name)};`,
            )
          ).stdout.trim(),
        ),
      });
    const invalidIndexes = await jsonQuery(
      "SELECT coalesce(json_agg(x),'[]') FROM (SELECT indexrelid::regclass::text AS name,indisvalid,indisready FROM pg_index WHERE NOT indisvalid OR NOT indisready) x;",
    );
    return { schema, tables: counts, invalidIndexes };
  }
  try {
    temp = await mkdtemp(join(tmpdir(), "mfr-rehearsal-"));
    await lock.writeFile(JSON.stringify({ pid: process.pid, runId, temp }));
    await mkdir(directory, { mode: 0o700 });
    await writeFile(join(directory, "migration.sql"), proposedSql, {
      mode: 0o600,
    });
    const statements = await parseMigration(proposedSql);
    if (![PROFILE, "submitted-transactions"].includes(executionProfile))
      throw new Error("Unknown execution profile");
    if (executionProfile === PROFILE && !backupOnly) {
      await validateAtomic(proposedSql);
      await validateChecks(checks);
    }
    if (!Array.isArray(checks) || checks.length > 30)
      throw new Error("At most 30 postconditions are supported.");
    const checkQueries = new Map();
    for (const check of checks) {
      const parsed = await parse(check.sql);
      if (
        parsed.stmts?.length !== 1 ||
        !parsed.stmts[0].stmt.SelectStmt ||
        !Object.hasOwn(check, "expectedRows")
      )
        throw new Error("Postconditions require one SELECT and expectedRows.");
      const stmt = parsed.stmts[0];
      const start = stmt.stmt_location ?? 0;
      const bytes = Buffer.from(check.sql);
      checkQueries.set(
        check,
        bytes
          .subarray(start, stmt.stmt_len ? start + stmt.stmt_len : bytes.length)
          .toString("utf8"),
      );
    }
    const env = await sourceEnvironment();
    const identity = JSON.parse(
      (
        await run(
          [
            ...sourceArgs,
            "psql",
            "-X",
            "-h",
            "127.0.0.1",
            "-d",
            sourceDatabase,
            "-At",
            "-v",
            "ON_ERROR_STOP=1",
          ],
          {
            env,
            input:
              "SELECT json_build_object('database',current_database(),'version',current_setting('server_version'),'bytes',pg_database_size(current_database()));",
          },
        )
      ).stdout.trim(),
    );
    assertSourceSize(Number(identity.bytes));
    Object.assign(report.source, identity);
    const sourceInfo = JSON.parse(
      (await run(["inspect", sourceContainer])).stdout,
    )[0];
    if (
      !sourceInfo.NetworkSettings.Ports?.["5432/tcp"]?.some(
        (port) => port.HostPort === "54329",
      )
    )
      throw new Error("Source port identity does not match allowlist.");
    report.clone.image = sourceInfo.Image;
    report.clone.snapshotStartedAt = new Date().toISOString();
    const archive = join(temp, "source.dump");
    await run(
      [
        ...sourceArgs,
        "pg_dump",
        "-h",
        "127.0.0.1",
        "-d",
        sourceDatabase,
        "-Fc",
        "--no-owner",
        "--no-acl",
      ],
      { env, outputFile: archive },
    );
    report.clone.snapshotFinishedAt = new Date().toISOString();
    await run([
      "run",
      "-d",
      "--name",
      name,
      "--label",
      `${labelKey}=${runId}`,
      "--network",
      "none",
      "--cpus",
      "2",
      "--memory",
      "2g",
      "--memory-swap",
      "2g",
      "--pids-limit",
      "128",
      "--cap-drop",
      "ALL",
      "--security-opt",
      "no-new-privileges",
      "--read-only",
      "--user",
      "70:70",
      "--tmpfs",
      "/var/lib/postgresql/data:rw,noexec,nosuid,uid=70,gid=70,size=1536m",
      "--tmpfs",
      "/var/run/postgresql:rw,noexec,nosuid,uid=70,gid=70,size=16m",
      "--tmpfs",
      "/tmp:rw,noexec,nosuid,uid=70,gid=70,size=64m",
      "-e",
      "POSTGRES_HOST_AUTH_METHOD=trust",
      "-e",
      "POSTGRES_DB=rehearsal",
      sourceInfo.Image,
      "postgres",
      "-c",
      "listen_addresses=",
      "-c",
      "statement_timeout=30000",
      "-c",
      "lock_timeout=2000",
    ]);
    for (let attempt = 0; ; attempt++) {
      try {
        await exec(["pg_isready", "-U", "postgres", "-d", "rehearsal"]);
        break;
      } catch (error) {
        if (attempt >= 40 || controller.signal.aborted) throw error;
        await new Promise((done) => setTimeout(done, 500));
      }
    }
    await psql(
      "CREATE ROLE rehearsal_owner LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS; ALTER DATABASE rehearsal OWNER TO rehearsal_owner; REVOKE CREATE ON SCHEMA public FROM PUBLIC; GRANT ALL ON SCHEMA public TO rehearsal_owner;",
      "postgres",
    );
    await restoreArchive(exec, archive);
    report.clone.restore = "SUCCEEDED";
    const sandboxInfo = JSON.parse((await run(["inspect", name])).stdout)[0];
    if (
      sandboxInfo.HostConfig.NetworkMode !== "none" ||
      sandboxInfo.Mounts.some((mount) => mount.Type !== "tmpfs") ||
      (sandboxInfo.HostConfig.PortBindings &&
        Object.keys(sandboxInfo.HostConfig.PortBindings).length)
    )
      throw new Error("Sandbox isolation invariant failed.");
    report.clone.isolationVerified = {
      network: sandboxInfo.HostConfig.NetworkMode,
      privileged: sandboxInfo.HostConfig.Privileged,
      readOnlyRoot: sandboxInfo.HostConfig.ReadonlyRootfs,
      mounts: sandboxInfo.Mounts.map((mount) => ({
        type: mount.Type,
        destination: mount.Destination,
      })),
      memoryBytes: sandboxInfo.HostConfig.Memory,
      nanoCpus: sandboxInfo.HostConfig.NanoCpus,
    };
    report.clone.version = (await psql("SHOW server_version;")).stdout.trim();
    if (report.clone.version !== report.source.version)
      throw new Error("Clone PostgreSQL version differs from source.");
    const before = await snapshot();
    report.before = before;
    const logicalQuery = async (sql) =>
      jsonQuery(
        `SELECT coalesce(json_agg(mfr_row),'[]') FROM (${sql}) mfr_row;`,
      );
    if (executionProfile === PROFILE || backupOnly) {
      await assertExecutionEnvironment(logicalQuery);
      report.baselineFingerprint = await fingerprint(logicalQuery);
    }
    if (backupOnly) {
      const retained = join(directory, "verified-backup.dump");
      await copyFile(archive, retained);
      report.backup = {
        archive: retained,
        sha256: createHash("sha256")
          .update(await readFile(retained))
          .digest("hex"),
        restoreVerified: true,
      };
      report.verification = { status: "PASSED", checks: [] };
      report.status = "BACKUP_RESTORE_VERIFIED";
      return { runId, directory, report };
    }
    const marker = `MFR_${randomUUID().replaceAll("-", "")}`;
    const atomic = executionProfile === PROFILE;
    const precommitChecks = atomic
      ? checks.map(
          (check) =>
            `SELECT CASE WHEN coalesce(jsonb_agg(mfr_check),'[]'::jsonb) = '${JSON.stringify(check.expectedRows).replaceAll("'", "''")}'::jsonb THEN 1 ELSE (1 / (count(*)-count(*)))::int END AS postcondition_passed FROM (${checkQueries.get(check)}) mfr_check;`,
        )
      : [];
    const script =
      [
        "\\set ON_ERROR_STOP on",
        "\\set VERBOSITY verbose",
        "\\timing on",
        ...(atomic ? ["BEGIN;", "SET LOCAL search_path=pg_catalog;"] : []),
        ...statements.flatMap((statement, i) => [
          `\\echo ${marker}_BEGIN_${i}`,
          statement.sql + "\n;",
          `\\echo ${marker}_END_${i}`,
        ]),
        ...precommitChecks,
        ...(atomic ? ["COMMIT;", `\\echo ${marker}_COMMITTED`] : []),
      ].join("\n") + "\n";
    let output;
    let executionError;
    try {
      output = await exec(
        [
          "psql",
          "-X",
          "-U",
          "rehearsal_owner",
          "-d",
          "rehearsal",
          "-v",
          "ON_ERROR_STOP=1",
        ],
        { input: script, timeout: 600_000 },
      );
    } catch (error) {
      output = error;
      executionError = error;
    }
    await writeFile(join(directory, "execution.stdout"), output.stdout ?? "", {
      mode: 0o600,
    });
    await writeFile(join(directory, "execution.stderr"), output.stderr ?? "", {
      mode: 0o600,
    });
    let transactionOpen = false;
    for (let i = 0; i < statements.length; i++) {
      const begin = `${marker}_BEGIN_${i}`;
      const end = `${marker}_END_${i}`;
      const stdout = output.stdout ?? "";
      const start = stdout.indexOf(begin);
      const finish = stdout.indexOf(end);
      const status =
        start < 0 ? "NOT_RUN" : finish < 0 ? "FAILED" : "COMPLETED";
      const result =
        start < 0
          ? ""
          : stdout
              .slice(start + begin.length, finish < 0 ? undefined : finish)
              .trim();
      if (
        status === "COMPLETED" &&
        ["TRANS_STMT_BEGIN", "TRANS_STMT_START"].includes(
          statements[i].transaction,
        )
      )
        transactionOpen = true;
      if (
        status === "COMPLETED" &&
        ["TRANS_STMT_COMMIT", "TRANS_STMT_ROLLBACK"].includes(
          statements[i].transaction,
        )
      )
        transactionOpen = false;
      report.execution.statements.push({
        index: i + 1,
        ...statements[i],
        status,
        result,
        milliseconds: Number(result.match(/Time: ([\d.]+) ms/)?.[1] ?? 0),
      });
    }
    report.execution.status = executionError
      ? "FAILED"
      : transactionOpen
        ? "UNCOMMITTED"
        : "SUCCEEDED";
    report.execution.transactionAtDisconnect = atomic
      ? executionError
        ? "ATOMIC_ROLLED_BACK"
        : "ATOMIC_COMMITTED"
      : transactionOpen
        ? "OPEN_TRANSACTION_ROLLED_BACK"
        : "NO_OPEN_TRANSACTION";
    if (executionError)
      report.execution.error = {
        message: executionError.message,
        stderr: output.stderr,
        sqlstate: output.stderr?.match(/ERROR:\s+([A-Z0-9]{5}):/)?.[1],
      };
    const after = await snapshot();
    report.after = after;
    if (atomic) report.afterFingerprint = await fingerprint(logicalQuery);
    report.diff = {
      schemaChanged: before.schema !== after.schema,
      tables: [
        ...new Set(
          [...before.tables, ...after.tables].map(
            (t) => `${t.schema}.${t.name}`,
          ),
        ),
      ].map((name) => ({
        name,
        beforeRows:
          before.tables.find((t) => `${t.schema}.${t.name}` === name)?.rows ??
          null,
        afterRows:
          after.tables.find((t) => `${t.schema}.${t.name}` === name)?.rows ??
          null,
      })),
      invalidIndexes: after.invalidIndexes,
    };
    for (const check of checks) {
      try {
        // Separate read-only session after migration disconnect, never the migration transaction.
        const rows = await jsonQuery(
          `BEGIN READ ONLY;\nSELECT coalesce(json_agg(mfr_check),'[]') FROM (${checkQueries.get(check)}\n) mfr_check;\nCOMMIT;`,
        );
        report.verification.checks.push({
          ...check,
          actualRows: rows,
          passed: isDeepStrictEqual(rows, check.expectedRows),
        });
      } catch (error) {
        report.verification.checks.push({
          ...check,
          passed: false,
          error: error.message,
        });
      }
    }
    report.verification.status = !checks.length
      ? "INCOMPLETE"
      : report.verification.checks.every((check) => check.passed) &&
          !after.invalidIndexes.length
        ? "PASSED"
        : "FAILED";
    report.status =
      report.execution.status !== "SUCCEEDED"
        ? "REHEARSAL_FAILED"
        : report.verification.status === "FAILED"
          ? "VERIFICATION_FAILED"
          : "REHEARSAL_COMPLETED";
  } catch (error) {
    report.status = controller.signal.aborted
      ? "INTERRUPTED_OR_DEADLINE"
      : "PREPARATION_OR_EVIDENCE_FAILED";
    report.error = error.message;
  } finally {
    clearTimeout(timer);
    process.removeListener("SIGINT", onSignal);
    process.removeListener("SIGTERM", onSignal);
    // Inspect ownership even if docker run succeeded but its response was interrupted.
    try {
      await removeSandbox(name, runId);
    } catch (error) {
      cleanupOK = false;
      report.cleanupError = error.message;
    }
    if (temp)
      await rm(temp, { recursive: true, force: true }).catch((error) => {
        cleanupOK = false;
        report.cleanupError = error.message;
      });
    report.cleanup = cleanupOK
      ? "REMOVED_EPHEMERAL_RESOURCES"
      : "NEEDS_CLEANUP";
    report.finishedAt = new Date().toISOString();
    report.elapsedMs = Date.now() - started;
    await mkdir(directory, { recursive: true, mode: 0o700 });
    await writeFile(
      join(directory, "report.json"),
      JSON.stringify(report, null, 2),
      { mode: 0o600 },
    );
    await writeFile(join(directory, "report.md"), markdown(report), {
      mode: 0o600,
    });
    await lock.close();
    if (cleanupOK) await rm(lockPath, { force: true });
  }
  return { runId, directory, report };
}
